name: "Required Checks"

on: pull_request

jobs:
  jest-tests:
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: ./.github/actions/install-node-dependencies

      - name: Jest Tests
        run: |
          npx jest --ci --silent --maxWorkers=1
        shell: bash
